# Biblioteca Numpy

### Tipo básico: NDARRAY

Estrutura básica para se trabalhar com NumPy são os arrays. Os arrays possuem dimensão fixa, definida durante a criação.

Propriedades básicas de um NDARRAY

* ndarray.ndim -> Número de dimensões
* ndarray.shape -> tupla de inteiros que indica o tamanho de cada dimensão
* ndarray.size -> Número total de elementos no array
* ndarray.dtype -> Tipo dos elementos contidos no array

In [1]:
import numpy as np
array = np.array([[5,7,9],[6,8,10]]) # criando um NDARRAY com base em listas
print(array)

[[ 5  7  9]
 [ 6  8 10]]


In [2]:
print(array.ndim)

2


In [3]:
print(array.shape)

(2, 3)


In [4]:
print(array.dtype)

int32


In [5]:
print(array.size)

6


### Criação de NDARRAY

Criando um array de dimensões 4x3 preenchidos com zeros

In [6]:
array_zeros = np.zeros((4,3))
print(array_zeros)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


Criando um array de dmensões 4x3 preenchidos com uns

In [7]:
array_ones = np.ones((4,3))
print(array_ones)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


Criando um array preenchido com números aleatórios que dependem do estado da memória

In [8]:
array_empty = np.empty((5,3))
print(array_empty)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


Cria array preenchido com números pertencentes à um dado intervalo espaçados de determinado valor

In [9]:
array_arange = np.arange(10,30,5) # de 10 a 19 de 5 em 5
print(array_arange)

[10 15 20 25]


### Funções básicas aplicadas sobre um array
* np.exp(V)
* np.sqrt(V)
* np.add(V.U)

### NDARRAY - Indexação
* ndarray[i] -> retorna o conteúdo da posição i
* ndarray[i:j] -> retorna os valores armazenados nas posições de i até j-1
* ndarray[i.j.k] -> indexação multidimensional
* ndarray[:.1] -> todas as linhas da segunda coluna
* ndarray[1.:] -> todas as colunas da segunda linha

Os modos de indexação podem ser combinados de forma a obter diferentes resultados

### Interação com NDARRAY

A iteração sobre um NDARRAY pode ser feita da mesma forma que as listas. Para cada dimensão do array se utiliza um for para chegar até os elementos.

In [10]:
array = np.array([[1,2,3],[4,5,6],[7,8,9]])

for linha in array:
    for coluna in linha:
        print(coluna)

1
2
3
4
5
6
7
8
9


### Iteração utilizando flat
O Numpy oferece uma maneira mais simples de se iterar sobre os elementos unitários de um array multidimensional utilizando a propriedade flat

In [11]:
array = np.array([[1,2,3],[4,5,6],[7,8,9]])
for item in array.flat:
    print(item)

1
2
3
4
5
6
7
8
9


### NDARRAY - manipulação de forma
O Numpy permite que o usuário mude a forma do vetor, aumentando ou diminuindo suas dimensões distribuindo os elementos entre as dimensões.


Por exemplo, um vetor com 10 elementos em apenas uma dimensão pode ser manipulado de forma que passe a ter duas dimensões 5 e 2.

Neste exemplo, temos uma matriz bidimensional onde foi especificado que cada linha deve conter 5 elementos a cada coluna 2 elementos.

In [12]:
array = np.array([1,2,3,4,5,6,7,8,9,10])
print(array.shape)

(10,)


In [13]:
novo_array = array.reshape(5,2)
print(novo_array)
print("Shape: ", novo_array.shape)

[[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]]
Shape:  (5, 2)
